### ISSUE TITLE
显示为空

### ISSUE THREAD

**Issue by ICT-Gavin** [RDSunhy/android-word2html#2]
您好，为什么我打开这个工程添加了动态权限也还是报open failed: EACCES (Permission denied)错误，另外webView预览显示空的

**Comment by RDSunhy** [comment]
是androidQ吗？如果是androidQ的话需要特殊处理下；webview是空应该就是没拿到文件，生成的html是空的；

**Comment by ICT-Gavin** [comment]
嗯，是安卓10手机。 我看了下picTextDoc.html这个文件手机上面生成了，但是是空的，然后picTextDoc.docx 这个文件没有生成（WordUtils.java:170）显示这里有问题，请问该怎么解决嘞

**Comment by RDSunhy** [comment]
picTextDoc 你应该改成你需要预览的 word 文件的位置。直接运行是不行的。

**Comment by ICT-Gavin** [comment]
嗯，改了下位置，可以预览了，谢谢哇。

**Comment by ICT-Gavin** [comment]
嗯，改了下位置，可以预览了，谢谢哇。
